import AppKit

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []

        // Respect apps (e.g. password managers) that mark copies as concealed/transient.
        let ignoredRawTypes: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        if types.contains(where: { ignoredRawTypes.contains($0.rawValue) }) {
            return
        }

        if types.contains(.tiff) || types.contains(.png) {
            if let image = NSImage(pasteboard: pasteboard) {
                HistoryStore.shared.addImage(image)
                return
            }
        }

        if types.contains(.string), let text = pasteboard.string(forType: .string) {
            HistoryStore.shared.addText(text)
        }
    }
}
